sudo: false
language: go
go_import_path: github.com/uber/athenadriver

env:
  global:
    - GO111MODULE=on

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"


matrix:
  include:
  - go: 1.12.x
  - go: 1.13.x
    env: LINT=1

install:
  - make install

script:
  - test -z "$LINT" || make lint
  - make test
  - fossa init
  - cd go && fossa analyze go

notifications:
  webhooks: https://app.fossa.io/hooks/travisci

after_success:
  - make cover
  - cd go && fossa test
